services:
  mqtt:
    hostname: tcp://localhost
    port: 1883
    username: mqtt-listener
    password: test
    clientName: mqtt-listener
    topic: mqtt-listener/test-data
  kafka:
    topic: mqtt-listener-topic
    brokers: localhost:9092